# This is a basic workflow to help you get started with Actions

name: Obfuscate_to_main

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: src
          path: b_src

      # Runs a single command using the runners shell
      - name: Remove Remote
        working-directory: b_src
        run: find . -type f | grep -i "\.git" | xargs rm

      - name: Install obfuscator
        run: npm install --save-dev javascript-obfuscator

      - name: Obfuscar
        run: |
          javascript-obfuscator sccore.js --output sccore.js 
      - name: Checkout code from master branch
        uses: actions/checkout@v2
        with:
          ref: main
          path: b_main

      # Copy files from b_code into b_master, the new obfuscated JavaScript files
      # will be copied to overwrite the old obfuscated JavaScript files in b_master.
      - name: Copy files
        run: cp -r b_src/*.js b_main

      - name: Push to remote main branch
        working-directory: b_main
        run: |
          git config --global user.name "easyappdev"
          git config --global user.email "darioescobar@gmail.com"
          git add -A
          git commit -m "Obfuscate JavaScript code"
          git push
